[package]
name = "from-str-sequencial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
from-str-sequencial-derive = { path = "from-str-sequencial-derive" }